version: "3.6"
services:
  wonderlabz:
    build:
      context: .
    networks:
      - proxy
      - internal
    ports:
      - 8181:80
    volumes:
      - ./src/html:/var/www/html
      - ./src/conf:/etc/nginx/templates
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.wonderlabz.entrypoints=https"
      - "traefik.http.routers.wonderlabz.tls=true"
      - "traefik.http.routers.wonderlabz.tls.certresolver=cloudflare"
      - "traefik.http.routers.wonderlabz.rule=Host(`wonderlabz-test.botes.family`)"
      - "traefik.http.services.wonderlabz-service.loadbalancer.passhostheader=true"
      - "traefik.http.services.wonderlabz-service.loadbalancer.server.port=80"
      - "traefik.http.services.wonderlabz-service.loadbalancer.server.scheme=http"
      - "traefik.http.routers.wonderlabz.middlewares=public-chain@file"

  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src/html:/var/www/html
    networks:
      - internal
  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ=Africa/Johannesburg
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 2 * * 0
      - WATCHTOWER_ROLLING_RESTART=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    external: true
  internal: